### ISSUE TITLE
two blacks, whites and transparent

### ISSUE THREAD

**Issue by aimichal** [allenai/varnish#59]
What's the difference? Why are there two ways to specify these colors?

```
theme.palette.common.black
theme.palette.common.white
theme.palette.common.transparent
```

```
theme.color.black
theme.color.white
theme.color.transparent
```

**Comment by jonborchardt** [comment]
Either is fine.

**Comment by jonborchardt** [comment]
Sratch that. I'll reply correctly when I get to a PC.

**Comment by jonborchardt** [comment]
theme.palette can (in the future) be overridden... so someone may want theme.palette.text.primary to be R2 instead of N6....

this could also override what black or white is...

theme.color.x will not be overridable....
so... whenever possible use theme.palette...  but feel free to use theme.color if you are doing something that is not in the palette.... like a fancy border...
